PGSBoard/Models/Board.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PGSBoard.Models
{
    public class Board
    {
        public Board()
        {
            Lists = new HashSet<List>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [MinLength(5)]
        public string Description { get; set; }

        public virtual ICollection<List> Lists { get; private set; }
    }
}

PGSBoard/ViewModels/BoardsViewModel.cs
using PGSBoard.Dtos;

namespace PGSBoard.ViewModels
{
    using System.Collections.Generic;
    using System.Web.Mvc;

    public class BoardsViewModel
    {
        public BoardsViewModel(IEnumerable<BoardDto> boards)
        {
            this.BoardsItems = new SelectList(boards, "Id", "Name");
        }

        public int SelectedBoardId { get; set; }

        public IEnumerable<SelectListItem> BoardsItems { get; set; }
    }
}

PGSBoard/ViewModels/CreateBoardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGSBoard.ViewModels
{
    using PGSBoard.Dtos;

    public class CreateBoardViewModel
    {
        public CreateBoardFormDto CreateBoardFormDto { get; set; }
    }
}

PGSBoard/Controllers/BoardController.cs
namespace PGSBoard.Controllers
{
    using System.Web.Mvc;

    using PGSBoard.Dtos;
    using PGSBoard.Services;

    public class BoardController : Controller
    {
        private readonly BoardsService _boardsService;   

        public BoardController()
        {
            this._boardsService = new BoardsService(); // We have to initialize boardService
        }
        // GET method that return view of creating board form  
        public ActionResult CreateBoard()
        {
            var viewModel = this._boardsService.GetCreateBoardViewModel();  //We are getting viewModel from service and pass it into view
            return this.View(viewModel);
        }

        // POST method that takes CreateBoardDto checks if it is valid as an argument and calls add CreateBoard moethod from boardsService
        // and then it redirects you to Index view (you can check that your new Board is available there)
        [HttpPost]
        public ActionResult CreateBoard([Bind(Prefix = "CreateBoardFormDto")] CreateBoardFormDto dto)  //We need bind attribute because:
                                    //CreateBoardFormDto is member of ShowBoardsViewModel which is model of Create view, as you can see in this view
                                    //in helpers texboxfor we tells ASP that this field is for m.CreateBoardFormDto.Name so ASP will name this input field
                                    //CreateBoardFormDto_Name - and there is a problem because CreateBoardFormDto has no field CreateBoardFormDto_Name, it has
                                    //only Name field so we need tell ASP that in this form names there is a prefix CreateBoardFormDto
        {
            if (this.ModelState.IsValid)  //We need to check if our dto is valid (see validation attributes in dto)
            {
                this._boardsService.CreateBoard(dto); //If is valid we are calling create board service
                return RedirectToAction("Index");  //After it redirect to Index view
            }
            var viewModel = this._boardsService.GetCreateBoardViewModel();  //If dto is invalid create viewmodel again
            viewModel.CreateBoardFormDto = dto;  //Pass there invalid dto to not lose information from all fields user filled
            return View(viewModel);   //Show Create board view again
        }

        // GET: return the main view of our app with BoardsViewModel 
        public ActionResult Index()
        {
            var viewModel = _boardsService.GetBoardsViewModel();
            return View(viewModel);
        }

        //GET: it takes from service viewModel of board which id equals SelectedBoardId and displays it
        public ActionResult Show(int SelectedBoardId)
        {
            var viewModel = _boardsService.GetShowBoardViewModel(SelectedBoardId);
            return View(viewModel);
        }

        //POST: Creates new list and redirecting to Show board with id of board to which we have just added list
        [HttpPost]
        public ActionResult CreateList(CreateListDto dto)
        {
            _boardsService.CreateList(dto);
            return RedirectToAction("Show", new { SelectedBoardId = dto.BoardId});
        }

        //POST: Creates new card and redirecting to Show board with id of board to which we have just added card
        [HttpPost]
        public ActionResult CreateCard(CreateCardDto dto)
        {
            int boardId = _boardsService.CreateCart(dto);
            return RedirectToAction("Show", new { SelectedBoardId = boardId });
        }

        //DELETE: Delete card from db and returns if action was successful
        [HttpDelete]
        public JsonResult DeleteCard(int cardId)
        {
            var deleteCardDto = new DeleteCardDto()
            {
                CardId = cardId
            };
            var result = _boardsService.DeleteCard(deleteCardDto);
            return new JsonResult()
            {
                Data = result
            };
        }

        [HttpDelete]
        public JsonResult DeleteList(int listId)
        {
            var deleteListDto = new DeleteListDto()
            {
                ListId = listId
            };

            var result = _boardsService.DeleteList(deleteListDto);
            return new JsonResult()
            {
                Data = result
            };
        }
    }
}

PGSBoard/Views/Board/CreateBoard.cshtml
@model PGSBoard.ViewModels.CreateBoardViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>CreateBoard</title>
</head>
<body>
    <!--FORMA-->
<div class="container card--white">
    @using (Html.BeginForm("CreateBoard","Board", FormMethod.Post))
    {
        <div class="row">
            <h3 class="col-md-12">Dodaj nową tablicę:</h3>
        </div>
        <div class="row">
            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.CreateBoardFormDto.Name)
                @Html.TextBoxFor(m => m.CreateBoardFormDto.Name, 
               new {@class = "form-control"})
               @Html.ValidationMessageFor(m => m.CreateBoardFormDto.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 form-group">
               @Html.LabelFor(m => m.CreateBoardFormDto.Description)
                @Html.TextAreaFor(m => m.CreateBoardFormDto.Description,
               new { @class = "form-control" })
               @Html.ValidationMessageFor(m => m.CreateBoardFormDto.Description)
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary" value="Dodaj!" />
            </div>
        </div>
    }
</div>
    <!--FORMA-->
</body>
</html>

PGSBoard/Views/Board/Index.cshtml
@model PGSBoard.ViewModels.BoardsViewModel

<!DOCTYPE html>
<html>

<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <meta charset="UTF-8">
</head>

<body>
    <div class="container">
        <header class="row">
            <h2 class="col-md-6">Twoje Tablice</h2>
        </header>
        <main class="row">
            <section class="col-md-6">
                <div class="row">
                    <h3 class="col-md-12">Wybierz tablice:</h3>
                </div>
                @using (Html.BeginForm("Show", "Board", FormMethod.Get))// For possiblity tp redirect user to board he chosen 
                                                                         // I've created form,which on submit sends GET request with id of chosen board
                {
                    <div class="row">
                        <div class="col-md-10">
                            @Html.DropDownListFor(m => m.SelectedBoardId, Model.BoardsItems,
                                new {@class = "form-control"})
                        </div>
                        <div class="col-md-2">
                            <input type="submit" class="btn btn-primary" value="Przejdz"/>
                        </div>
                    </div>
                }
            </section>
            <section class="col-md-6">
                @Html.ActionLink("Create Board", 
               "CreateBoard", "Board", null,
               new { @class = "btn btn-primary"})
            </section>
        </main>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.js"></script>
</body>

</html>

PGSBoard/Views/Board/Show.cshtml
@model PGSBoard.ViewModels.ShowBoardViewModel

@{
    ViewBag.Title = "title";

}

@*This is new view, this view is showing a board which user has chosen. This will be most important view in app.
    I've add it here because we didn't had time to create it last time.*@

<div class="container-fluid">
    <header class="row">
        <h1 class="col-md-3 col-md-offset-1">@Model.Name</h1> @*Show board name*@
    </header>
    <main class="row">
        <div class="col-md-12">
            <div class="board">
                <!--LIST-->
                @foreach (var list in Model.Lists)  //Iterate all lists in board and display it
                {
                    <section data-list-id="@list.Id" class="list">
                        <header class="list__header clearfix">
                            <h4 class="pull-left">@list.Name</h4> @*Display list name*@
                            <i class="fa fa-trash-o trash pull-right list__remove-list-btn"></i>
                        </header>
                        <div class="list__cards-container ui-sortable">
                            @foreach (var card in list.Cards) //Iterate all cards in list
                            {
                                <!--card-->
                                <div class="card">
                                    <div class="card__header clearfix">
                                        <h5 class="pull-left">@card.Name</h5> @*Display card name*@
                                        <i class="fa fa-trash-o trash pull-right card__remove-card-btn" data-card-id="@card.Id"></i>
                                    </div>
                                    <div class="card__body">
                                        @card.Description @*Display card description*@
                                    </div>
                                </div> 
                            }
                            <!--card-->
                        </div>
                        <!--cardForm-->
                        @Html.Partial("_CreateCardForm", list.CreateCardDto) @*As last card display form to creating card, we didn't talk about
                                                                                 partials - but it's simple way to paste html code form other file
                                                                                 Whats more we can pass there it's own model. In this case it is createCardDto*@
                        <!--cardForm-->
                    </section>
                }
                <!--LIST-->
                @Html.Partial("_CreateListForm", Model.CreateListDto) @*Like in cards as last list we display form for creating list, it works in the same way
                                                                          as adding carD. There is used partial to injiect html code*@
            </div>
        </div>
    </main>
    @section scripts{
        @Scripts.Render("~/bundles/cardBundle")
    }
</div>

PGSBoard/Views/Board/_CreateCardForm.cshtml
@model PGSBoard.Dtos.CreateCardDto

@*This partial will be injected to show boards view and it is form for creating new card*@

<div class="card card--editor clearfix hidden-form">
    @using (Html.BeginForm("CreateCard", "Board", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.ListId) @*In hidden html field we put id of list to which card will be added, during creating this dto,
                                           we put there id of list and now we can pass it to server again*@
        <div class="form-group card__header">
            @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
        </div>
        <div class="form-group card__body">
            @Html.TextAreaFor(m => m.Description, new {@class = "form-control"})
        </div>
        <div>
            <input type="submit" value="Dodaj" class="btn btn-primary pull-right"/>
        </div>
    }
</div>
<button class="pull-right btn btn-success">Dodaj karte</button>

PGSBoard/Views/Board/_CreateListForm.cshtml
@model PGSBoard.Dtos.CreateListDto

@*This partial will be injected to show boards view and it is form for creating new list*@

<section class="list">
    @using (Html.BeginForm("CreateList", "Board", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.BoardId)
        <div class="form-group">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
        <div>
            <input type="submit" class="btn btn-success" value="Dodaj listę"/>
        </div>
    }
</section>